version: '3.8'

services:
  voting-app:
    build: .
    container_name: voting-backend
    ports:
      - "8080:8080"
    volumes:
      - ./votes.json:/app/votes.json
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped